trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        mkdir -p ~/.docker
        sed '$ s/.$//' $DOCKER_CONFIG/config.json > ~/.docker/config.json
        echo ',"experimental": "enabled" }' >> ~/.docker/config.json
        sudo service docker restart
        docker version
        docker buildx --help