trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use - docker buildx create --use
        docker buildx inspect --bootstrap - docker buildx inspect --bootstrap
        docker buildx build --platform=linux/amd64,linux/arm64 -t ymedlop/konga:latest .