trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  DOCKER_BUILD_KIT: 1
  DOCKER_CLI_EXPERIMENTAL: 'enabled'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '19.03.7'
        releaseType: 'edge'
    - bash: |
        mkdir -p ~/.docker/cli-plugins
        curl -L https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 --output ~/.docker/cli-plugins/docker-buildx
        chmod a+x ~/.docker/cli-plugins/docker-buildx
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
        docker buildx create --use
        docker buildx inspect --bootstrap
        docker login -u $(docker_user) -p $(docker_pwd)
        docker buildx build --platform=linux/amd64,linux/arm64 -t ymedlop/konga:0.14.7 -o type=registry .