trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - bash: |
        mkdir -p ~/.docker
        echo '{ "experimental": true }' | sudo tee /~/.docker/config.json
        sudo service docker restart
        docker version
        docker buildx --help